In [37]:
import numpy as np
import cv2
from scipy import ndimage
import matplotlib.pyplot as plt

In [38]:
def fspecial(filter_type, alpha=0.2):
    '''
    Creates a tow-dimensional filter of the specified type. Possible values for filter_type are:
        'laplacian'
        'unsharp'
    @param      filter_type      Type of desiered filter.
    @return     Numpy array containing coefficients of impulse response for the desired filter. 
    '''
    if (filter_type == 'laplacian'):
        a = max(0, min(alpha, 1))
        h1 = a/ (a + 1)
        h2 = (1 - a) / (a + 1)
        return np.array([[h1,       h2,     h1],
                         [h2, -4 / (a + 1), h2],
                         [h1,       h2,     h1]])

    elif (filter_type == 'unsharp'):
        aux = np.array([[0,  0,  0],
                         [0,  1,  0],
                         [0,  0,  0]])
        return aux - fspecial('laplacian', alpha)

In [39]:
h = fspecial('unsharp')
print(h)
b = cv2.imread('C:/Users/facun/OneDrive/Desktop/ITBA/9C_Procesamiento_de_Imagenes/image-processing-tp02/resources/barbara.jpg', cv2.IMREAD_GRAYSCALE)
cv2.imshow('Unfiltered', b)
cv2.waitKey(0)

[[-0.16666667 -0.66666667 -0.16666667]
 [-0.66666667  4.33333333 -0.66666667]
 [-0.16666667 -0.66666667 -0.16666667]]


13

In [40]:
h1 = cv2.filter2D(b, -1, h)
print(h1.shape)
cv2.imshow('Filtered', h1)
cv2.waitKey(0)
cv2.destroyAllWindows() 

(580, 720)


In [41]:
cv2.destroyAllWindows() 